language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - pipenv run python run_tests

after_success:
  - pipenv run codecov

branches:
  only:
    - master