language: python
python:
  - "3.6"
install:
  - pip install -r test-requirements.txt
  - pip install codecov
  - pip install coverage
script:
  - pytest --cov=ras_backstage --cov-report xml
  - coverage report

after_success:
  - codecov

branches:
  only:
    - master