import os


class Config(object):
    DEBUG = os.getenv('DEBUG', False)
    TESTING = False
    NAME = 'ras-backstage'
    VERSION = os.getenv('VERSION', '0.0.1')
    PORT = os.getenv('PORT', 8083)
    LOGGING_LEVEL = os.getenv('LOGGING_LEVEL', 'INFO')
    SECURITY_USER_NAME = os.getenv('SECURITY_USER_NAME')
    SECURITY_USER_PASSWORD = os.getenv('SECURITY_USER_PASSWORD')
    BASIC_AUTH = (SECURITY_USER_NAME, SECURITY_USER_PASSWORD)
    DJANGO_CLIENT_ID = os.getenv('DJANGO_CLIENT_ID')
    DJANGO_CLIENT_SECRET = os.getenv('DJANGO_CLIENT_SECRET')
    DJANGO_BASIC_AUTH = (DJANGO_CLIENT_ID, DJANGO_CLIENT_SECRET)
    JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
    JWT_SECRET = os.getenv('JWT_SECRET')

    OAUTH_SERVICE_HOST = os.getenv('OAUTH_SERVICE_HOST', 'localhost')
    OAUTH_SERVICE_PORT = os.getenv('OAUTH_SERVICE_PORT', 8040)
    OAUTH_SERVICE_PROTOCOL = os.getenv('OAUTH_SERVICE_PROTOCOL', 'http')
    OAUTH_SERVICE = '{}://{}:{}/'.format(OAUTH_SERVICE_PROTOCOL, OAUTH_SERVICE_HOST, OAUTH_SERVICE_PORT)
    OAUTH_TOKEN_URL = '{}api/v1/tokens/'.format(OAUTH_SERVICE)

    SECURE_MESSAGING_SERVICE_HOST = os.getenv('SECURE_MESSAGING_SERVICE_HOST', 'localhost')
    SECURE_MESSAGING_SERVICE_PORT = os.getenv('SECURE_MESSAGING_SERVICE_PORT', 5050)
    SECURE_MESSAGING_SERVICE_PROTOCOL = os.getenv('SECURE_MESSAGING_SERVICE_PROTOCOL', 'http')
    SECURE_MESSAGING_SERVICE = '{}://{}:{}/'.format(SECURE_MESSAGING_SERVICE_PROTOCOL, SECURE_MESSAGING_SERVICE_HOST, SECURE_MESSAGING_SERVICE_PORT)


class DevelopmentConfig(Config):
    DEBUG = os.getenv('DEBUG', True)
    LOGGING_LEVEL = os.getenv('LOGGING_LEVEL', 'DEBUG')
    SECURITY_USER_NAME = os.getenv('SECURITY_USER_NAME', 'test_user')
    SECURITY_USER_PASSWORD = os.getenv('SECURITY_USER_PASSWORD', 'test_password')
    BASIC_AUTH = (SECURITY_USER_NAME, SECURITY_USER_PASSWORD)
    DJANGO_CLIENT_ID = os.getenv('DJANGO_CLIENT_ID', 'test@test.test')
    DJANGO_CLIENT_SECRET = os.getenv('DJANGO_CLIENT_SECRET', 'testtest')
    DJANGO_BASIC_AUTH = (DJANGO_CLIENT_ID, DJANGO_CLIENT_SECRET)
    JWT_SECRET = os.getenv('JWT_SECRET', 'vrwgLNWEffe45thh545yuby')
