service:
    NAME: ras-backstage
    VERSION: 0.0.1
    SCHEME: http
    HOST: 0.0.0.0
    PORT: 8080
    DEBUG: True
    LOG_LEVEL: debug

dependencies:
    case-service:
        scheme: http
        host: localhost
        port: 8001
    collection-exercise-service:
        scheme: http
        host: localhost
        port: 8002
    collection-instrument-service:
        scheme: http
        host: localhost
        port: 8003
    survey-service:
        scheme: http
        host: localhost
        port: 8004
    secure-message-service:
        scheme: http
        host: localhost
        port: 8005
    party-service:
        scheme: http
        host: localhost
        port: 8006
    oauth2-service:
        scheme: http
        host: localhost
        port: 8000
        client_id: "ons@ons.gov"
        client_secret: "password"
