service:
    NAME: ras-backstage
    VERSION: 0.0.1
    SCHEME: http
    HOST: 0.0.0.0
    PORT: 8080
    DEBUG: True
    LOG_LEVEL: debug

dependencies:
    oauth2-service:
        scheme: http
        host: localhost
        port: 8000
        authorization_endpoint: "/web/authorize/"
        token_endpoint: "/api/v1/tokens/"
        admin_endpoint: "/api/account/create"
        activate_endpoint: "/api/account/activate"
        client_id: "ons@ons.gov"
        client_secret: "password"
    dummy-service:
      scheme: http
      host: localhost
      port: 5000
